### ISSUE TITLE
Algo-1/week3/7-Range-Minimum-Query/  wrong example answer

### ISSUE THREAD

**Issue by didizlatkova** [HackBulgaria/Algo-1#23]
I assume the search of the minimal element is inclusive, since one of the example inputs has equal start and end indexes ("min 15 15"). If that is the case, then the output of "min 0 7" should be 2 instead of 3 since 2 is at index 7 in the list at that time.

**Comment by itodorov** [comment]
"There are only two hard things in Computer Science: cache invalidation, naming things and off-by-one errors." :)

--fixed
